pipeline{
    agent any

    stages {
        stage('install dependancies'){
            steps{
                dir('invexo/client/react') {   
                    bat 'npm install'
                }
            }
        }
        stage('Build React App'){
            steps{
                dir('invexo/client/react'){
                    bat 'npm run build'
                }
            }
        }
    }
    post{
        success{
            echo "react app built successfully"
        }
        failure{
            echo "pipeline failed!"
        }
    }
}